### PR TITLE
🤖 fix(commentbot): comment when Project.toml fails to parse

### LINKED ISSUE #483: No response from registrator bot if Project.toml is not parseable
I struggled recently to register a new version of a package, getting [no responses](https://github.com/KristianHolme/Drill.jl/commit/45516465d21ff6b736c783788cb11894c4089f29) from the registrator bot. I tried uninstalling and reinstalling the app, commenting on both commits and issues, but nothing worked. 
Then i discovered that i had accidentally duplicated the sources section of the Project.toml, so the file would not parse.

It would have been very helpful if the registrator bot would have picked this up and commented accordingly. It's a basic mistake on my part, it but would have saved me many hours if the bot could have given me a heads up :)

### PR DESCRIPTION
**Pull request by KristianHolme**
- Handle TOML.ParserError and CompositeException/CapturedException
- Include parser showerror text in the GitHub reply message
- Fix RegistryTools.Project error reporting (use showerror, not broken e.msg)
- Wrap ProcessedParams in action() so preprocessing errors still notify users
- Add is_pfile_parseable unit tests

Made-with: Cursor

This hopefully fixes #483.
Most tests pass locally, but i have not tested if the problem from #483 is actually fixed. 
🤖 Code written by Cursor, but looks reasonable to me.

### CODE REVIEW

File: src/commentbot/verify_projectfile.jl [hunk 1]
```diff
@@ -86,10 +111,7 @@ function verify_projectfile_from_sha(reponame, commit_sha; auth=GitHub.Anonymous
                 try
                     project = RegistryTools.Project(TOML.parse(projectfile_contents))
                 catch ex
-                    err = "Failed to read project file"
-                    if isdefined(ex, :msg)
-                        err = err * ": $(e.msg)"
-                    end
+                    err = "Failed to read project file: " * sprint(showerror, ex)
```
Comment (nkottary) [inline src/commentbot/verify_projectfile.jl]: Would be good if you could beautify this message with some triple back ticks and unescaped newlines. It appears like this currently:

Image

File: src/commentbot/CommentBot.jl [hunk 2]
```diff
@@ -171,7 +171,17 @@ function action(rp::RequestParams{T}, zsock::RequestSocket) where T <: RegisterT
         end
     end
 
-    pp = ProcessedParams(rp)
+    local pp
+    try
+        pp = ProcessedParams(rp)
```
Comment (nkottary) [inline src/commentbot/CommentBot.jl]: This catch is unnecessary. Reporting is already handled below. Please undo all changes to this file.

**Review by nkottary — CHANGES_REQUESTED** [review]
Needs couple of changes otherwise looks good.

File: src/commentbot/verify_projectfile.jl [hunk 3]
```diff
@@ -1,20 +1,45 @@
...
-                @debug(err)
-                return false, err
-            else
-                rethrow(ex)
+            msg = _format_toml_parse_error(ex)
+            if msg !== nothing
+                @debug(msg)
+                return false, msg
             end
+            rethrow(ex)
```
Comment (ericphanson) [inline src/commentbot/verify_projectfile.jl]: in catch-blocks, prefer just `rethrow()` which will propograte the original exception stack. If you `rethrow(ex)` it starts a new nested exception stack pointing to the catch block. See [here](https://docs.julialang.org/en/v1/base/base/#Base.rethrow)
```suggestion
            rethrow()
```

File: src/commentbot/verify_projectfile.jl (hunk 1 above)
Comment (KristianHolme) [reply src/commentbot/verify_projectfile.jl]: Tried to fix this, but have not checked that a real comment looks good.

Before:
```julia
julia> println(err)
Could not parse (Julia)Project.toml as TOML: TOML Parser error:
none:84:-1 error: key already defined
  [sources.DrillInterface]
                         ^
```

After:

````julia
julia> println(err)
Could not parse (Julia)Project.toml as TOML:

```
TOML Parser error:
none:84:-1 error: key already defined
  [sources.DrillInterface]
                         ^
```
````

File: src/commentbot/CommentBot.jl (hunk 2 above)
Comment (KristianHolme) [reply src/commentbot/CommentBot.jl]: Done!

File: src/commentbot/verify_projectfile.jl (hunk 3 above)
Comment (KristianHolme) [reply src/commentbot/verify_projectfile.jl]: Thank you! This is fixed now.

File: src/commentbot/verify_projectfile.jl (hunk 1 above)
Comment (nkottary) [reply src/commentbot/verify_projectfile.jl]: The newlines are still escaped and the reason is the use of [`repr`](https://github.com/JuliaRegistries/Registrator.jl/blob/b6626c38c21b0a421037a6975a395a63b2a4d786/src/commentbot/CommentBot.jl#L207). Can you replace that with `something()`?

**Review by nkottary — APPROVED** [review]
LGTM!

File: src/commentbot/verify_projectfile.jl (hunk 1 above)
Comment (KristianHolme) [reply src/commentbot/verify_projectfile.jl]: I removed `repr`, so now `action` matches `comment_handler`, but did not replace with `something`. 
Did you mean just directly replace like `$(something(pp.cparams.error))`, or something else like `$(something(pp.cparams.error, "" ))`?

Comment (nkottary) [reply src/commentbot/verify_projectfile.jl]: I meant `$(something(pp.cparams.error, "" ))` but yeah just removing `repr` is correct.
